{{- if .Values.registry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: registry
  labels:
    {{- include "cluma.registry.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cluma.registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cluma.registry.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: registry
          image: "{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}"
          ports:
            - containerPort: {{ .Values.registry.service.port }}
          env:
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
            - name: REGISTRY_HTTP_ADDR
              value: "0.0.0.0:{{ .Values.registry.service.port }}"
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
          resources:
            {{- toYaml .Values.registry.resources | nindent 12 }}
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-pvc
{{- end }}
