apiVersion: v1
kind: Service
metadata:
  name: cluma-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluma.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "cluma.backend.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
