kubePrometheusStack:
  # Prometheus configuration
  prometheus:
    prometheusSpec:
      retention: 15d
      additionalScrapeConfigs:
        - job_name: dcgm-exporter
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              regex: dcgm-exporter
              action: keep
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              target_label: __address__
              regex: (.+)
              replacement: ${1}:9400

  # Grafana configuration
  grafana:
    enabled: true
    adminUser: admin
    adminPassword: admin
    defaultDashboardsEnabled: true

  # Node exporter
  nodeExporter:
    enabled: true

  # Prometheus Node Exporter subchart
  prometheus-node-exporter:
    enabled: true

  # Alert manager
  alertmanager:
    enabled: true
